//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUSICMAN.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adress
    {
        public Adress()
        {
            this.Shop = new HashSet<Shop>();
        }
    
        public int IdShopPlace { get; set; }
        public int IdStreet { get; set; }
        public string ShoppingCenter { get; set; }
        public int IdCountry { get; set; }
        public int IdCity { get; set; }
        public string HouseNumber { get; set; }
    
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual Streets Streets { get; set; }
        public virtual ICollection<Shop> Shop { get; set; }
    }
}
