//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUSICMAN.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.Adress = new HashSet<Adress>();
            this.Composer = new HashSet<Composer>();
            this.ProviderAdress = new HashSet<ProviderAdress>();
        }
    
        public int IdCountry { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Adress> Adress { get; set; }
        public virtual ICollection<Composer> Composer { get; set; }
        public virtual ICollection<ProviderAdress> ProviderAdress { get; set; }
    }
}
