//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUSICMAN.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProviderAdress
    {
        public ProviderAdress()
        {
            this.Provider = new HashSet<Provider>();
        }
    
        public int IdProviderAdress { get; set; }
        public int IdCountry { get; set; }
        public int IdCity { get; set; }
        public int IdStreet { get; set; }
        public int Home { get; set; }
    
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual ICollection<Provider> Provider { get; set; }
        public virtual Streets Streets { get; set; }
    }
}
