//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUSICMAN.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stocks
    {
        public Stocks()
        {
            this.Plates = new HashSet<Plates>();
        }
    
        public int IdStock { get; set; }
        public string StockNumber { get; set; }
        public string IndividualAdress { get; set; }
    
        public virtual ICollection<Plates> Plates { get; set; }
    }
}
