//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUSICMAN.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Streets
    {
        public Streets()
        {
            this.Adress = new HashSet<Adress>();
        }
    
        public int IdStreet { get; set; }
        public string Street { get; set; }
    
        public virtual ICollection<Adress> Adress { get; set; }
    }
}
