//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUSICMAN.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workers
    {
        public int IdWorkerInfo { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Number { get; set; }
        public string Email { get; set; }
        public Nullable<int> IdShop { get; set; }
        public byte[] PhotoStaff { get; set; }
        public int IdUser { get; set; }
    
        public virtual Shop Shop { get; set; }
        public virtual User User { get; set; }
    }
}
